name: one_code
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/resources.json 
    - assets/emergency_alerts.json 
    - assets/donations.json
    - assets/current_requests.json
    - assets/users.json
